### ISSUE TITLE
Callback event "Permission denied" is not invoked when Motion and Fitness permission is disabled in iPhone

### ISSUE THREAD

**Issue by bikcrum** [hypertrack/sdk-flutter#6]
## Description

Whenever "**Motion and Fitness**" permission is explicitly disabled from the iPhone's settings, it invokes a callback for `TrackingStateChange.permissions_denied` in HyperTrack SDK version 0.1.2. However, in the latest version of HyperTrack SDK for flutter which is 0.1.4, the callback for permission denial is not called. 

## Steps to reproduce
1. Use HyperTrack version [0.1.4](https://pub.dev/packages/hypertrack_plugin) for Flutter
1. Add a callback as following
```
// Initialization
hyperTrack = await HyperTrack.initialize(<HYPER_TRACK_PUBLISHABLE_KEY>);

// Add a callback
hyperTrack.onTrackingStateChanged.listen((TrackingStateChange event) async {
      print('hyperTrack.onTrackingStateChanged event: $event');
      switch (event) {
        case TrackingStateChange.start:
          // Invoked when tracking is started
          break;
        case TrackingStateChange.stop:
           // Invoked when tracking is stop
          break;
        case TrackingStateChange.permissions_denied:
           // Invoked when permission is denied
          break;
        case TrackingStateChange.location_disabled:
          // Invoked when location is disabled (GPS sensor turned off)
          break;
        case TrackingStateChange.invalid_token:
          // Invoked when token is invalid
          break;
        case TrackingStateChange.network_error:
          // Invoked for network error
          break;
        case TrackingStateChange.auth_error:
          // Invoked for authenticaiton error
          break;
        case TrackingStateChange.unknown_error:
          // Invoked for some unknown error
          break;
      }
});

// start method
hyperTrack.start();

// stop method
hyperTrack.stop();
```
2. Run your app on your iPhone. Initialize HyperTrack. It will ask for all required permissions when you call `hyperTrack.start()` in your app. After you allow all permissions, you will get a callback event for `TrackingStateChange.start`.
3. Now stop using `hyperTrack.stop()` in your app, you will get a callback event for `TrackingStateChange.stop`. All good till here.
4. Now go to your app settings and disable Motion and Fitness permission under your app.
5. Open the app again, try to Initialize, and start again. Nothing happens here, none of the callback events are invoked and thus can't find a way to know if tracking is started or not.

## Expected
In step 5 above, a callback for the event `TrackingStateChange.permissions_denied` should be invoked.
## Actual
In steps 5 above, none of the callback events are invoked

## Tested on
- iPhone 6 (OS: 12.4.9)
- iPhone X (OS: 14.2)
- iPhone X (OS: 14.1)

## Important note
This issue appears in HyperTrack SDK current version (0.1.4) but not in the previous version (0.1.2)

**Comment by DmitryShapovalov** [comment]
Hello @bikcrum. Thanks, that issue fixed in version [0.1.5](https://pub.dev/packages/hypertrack_plugin)
FYI: @deniszpua @tulushev

**Comment by DmitryShapovalov** [comment]
In version `0.1.5` I fixed the wrong definition of the error `permissions_error`. The fix for the callback will be added later since this requires the release of the iOS SDK update, I will notify you when this is fully fixed.

**Comment by bikcrum** [comment]
> In version `0.1.5` I fixed the wrong definition of the error `permissions_error`. The fix for the callback will be added later since this requires the release of the iOS SDK update, I will notify you when this is fully fixed.

Okay, thanks for letting me know.

**Comment by DmitryShapovalov** [comment]
Hello @bikcrum , issue with `Callback event "Permission denied"` already fixed in hypertrack_plugin version [1.6.0](https://pub.dev/packages/hypertrack_plugin)
If you have any questions, feel free to write to me. Have a nice day.

**Comment by bikcrum** [comment]
> Hello @bikcrum , the issue with `Callback event "Permission denied"` already fixed in hypertrack_plugin version [1.6.0](https://pub.dev/packages/hypertrack_plugin)
> If you have any questions, feel free to write to me. Have a nice day.

I upgraded to 1.6.0 but something strange happened:-

Reproduction steps:
1. I disabled motion and fitness permission on iPhone.
2. I launched the app and HyperTrack initialization was successful.
3. I called the start method on HyperTrack and got a permission error (as expected)
4. I ignored it and tried to hit start function again but didn't get any callback
    - Excepted: I should receive permission error as many as the time I invoke the start function
    - Actual: I only get it once after initialization
5. I closed the app and relaunched it.
6. HyperTrack initialization was successful and I tried to check if it's in running state and it returned true.
    -  Excepted: Hypertrack should not go active/running state because the start was not successful (due to permission error)
    -  Actual: Hypertrack showed active/running state 
7. I tried to stop running state by hitting stop function but again no callbacks were received.

**Comment by DmitryShapovalov** [comment]
Hi @bikcrum, at the moment the SDK is working correctly. A permissions error is sent to the user once a time when calling the `start()` method.
On the next attempts to start tracking, if the error does not change, that error is not sent to subscribers until the tracking intent is changed, after changing the intent, the SDK sends the error again.

Sequence example:

| SDK actions | system location permissions | system motion permissions | provided errors |
|-|:-:|:-:|-|
| SDK initialize() | NotDetermined | NotDetermined | - |
| SDK start() | Denied | Granted | loc.permissions.Denied |
| SDK start() | Denied | Granted | - |
| SDK stop() | Denied | Granted | - |
| SDK start() | Denied | Granted | loc.permissions.Denied |

also `isRunning` - reflects an intent to track, not the actual location tracking status. SDK may not track the user's location due to a permission error, but `isRunning` will return true - since SDK received the intent to track `hypertrack.start()`.

Our team is working on redesign the error return logic and the current status of the SDK. This will be added later.
If it is not convenient for you, we can update the current logic and generate notifications with errors for each start tracking call.

**Comment by bikcrum** [comment]
@DmitryShapovalov @deniszpua 

Thanks for letting me know. Actually, we are about to deploy our app to production and we need a fix as soon as possible. As you said, I think it is convenient to generate a notification for each `hypertrack.start()` call because it will align with the previous implementation (in version 0.1.2). 

We currently let the user dismiss permission request and that is why the user is able to hit on start() again. Unfortunately, the [library](https://github.com/Baseflow/flutter-permission-handler/issues/379) that I am using for permission handling is unable to determine if `motion and fitness permission` is enabled or not in iOS so I guess we only have one option.
