### ISSUE TITLE
Duplicate Classes if used any of the Firebase dependency

### ISSUE THREAD

**Issue by mrdishant** [hypertrack/sdk-flutter#9]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-2.6.1 (com.google.protobuf:protobuf-java:2.6.1) and jetified-protobuf-javalite-3.11.0 (com.google.protobuf:protobuf-javalite:3.11.0)

**Comment by deniszpua** [comment]
Hi @mrdishant. 
This is fixed since [v0.2.0](https://pub.dev/packages/hypertrack_plugin/versions/0.2.0)
